package lab1.model;

public enum ErrorType {
    INVALID_START,
    DOUBLE_OPERATOR,
    MISSING_OPERAND,
    SECOND_DECIMAL_DOT,
    MISSING_DIGIT_AFTER_DOT,
    MUL_DIV_AFTER_OPEN_BRACKET,
    MISSING_OPERATOR_BETWEEN,
    EMPTY_BRACKETS,
    EXTRA_CLOSING_BRACKET,
    MISSING_CLOSING_BRACKET,
    UNTERMINATED_EXPRESSION,
    UNKNOWN_SYMBOL,
    INVALID_IDENTIFIER_CHAR,
    MISSING_ARGUMENT,
    COMMA_OUTSIDE_FUNCTION
}
